# Getting Started with Python for People in a Hurry

## Using Markdown in Jupyter for Literate Programming

[Markdown Syntax](https://help.github.com/en/articles/basic-writing-and-formatting-syntax)

## Elements of Python

### Code and comments

In [1]:
# The code below makes a list of strings
["cesm", "cmip", "cam", "pop", "mom"]

['cesm', 'cmip', 'cam', 'pop', 'mom']

### Types

- **None**

In [2]:
None

- **Logical**

In [3]:
True, False

(True, False)

- **Numeric**

In [4]:
2, 2.46, 0, .3

(2, 2.46, 0, 0.3)

- **Strings**

Single and double quotes are suppported:

In [5]:
'The', 'Community Climate Model', "(CCM)", ' was created by NCAR in 1983'

('The', 'Community Climate Model', '(CCM)', ' was created by NCAR in 1983')

In [6]:
'''triple quoted strings
can span
multiple lines'''

'triple quoted strings\ncan span\nmultiple lines'

- **Special characters**

In [7]:
print('a b\nc\td e f')

a b
c	d e f


- **String interpolation**

Old style

In [8]:
'Both %s and %s are %s%d components' %('pop', 'cam', 'CESM', 2)

'Both pop and cam are CESM2 components'

In [9]:
'Both {} and {} are {}{} components'.format('pop', 'cam', 'CESM', 2)

'Both pop and cam are CESM2 components'

F-strings

In [10]:
component_1='pop'
component_2='cam'
cesm='CESM'
version=2

In [11]:
f'Both {component_1} and {component_2} are {cesm}{version} components'

'Both pop and cam are CESM2 components'

### Operators

- **Arithmetic**

In [12]:
-1

-1

In [13]:
2+3

5

In [14]:
7%3

1

In [15]:
7/2

3.5

In [16]:
7//2

3

In [17]:
2**4

16

- **Logical**

In [18]:
True and True

True

In [19]:
True & False

False

In [20]:
True | False

True

In [21]:
3 <= 4

True

In [22]:
3 == 4

False

In [23]:
3 != 4

True

In [24]:
3 > 4

False

### Variables and Assignments

In [25]:
a = 5
b = 10 
c = a + b

In [26]:
a, b, c

(5, 10, 15)

### Containers (Collections)

In [27]:
a_tuple = ('pop', 'mom', 'cam')
a_tuple

('pop', 'mom', 'cam')

In [28]:
a_list = ['pop', 'mom', 'cam']
a_list

['pop', 'mom', 'cam']

In [29]:
a_set = {'pop', 'mom', 'cam', 'mom', 'pop'}
a_set

{'cam', 'mom', 'pop'}

In [30]:
a_dict = {'component_1': 'pop', 'component_2': 'mom', 'component_3': 'cam'}
a_dict

{'component_1': 'pop', 'component_2': 'mom', 'component_3': 'cam'}

## Indexing a container

In [31]:
a_tuple[0]

'pop'

In [32]:
a_list[1:3]

['mom', 'cam']

In [33]:
a_dict['component_1']

'pop'

## Conversion between types

In [34]:
x = 123
x, type(x)

(123, int)

In [35]:
x = str(x)
x, type(x)

('123', str)

In [36]:
x = float(x)
x, type(x)

(123.0, float)

In [37]:
d = {'a': 1, 'b': 2}
d, type(d)

({'a': 1, 'b': 2}, dict)

In [38]:
list(d)

['a', 'b']

In [39]:
list(d.items())

[('a', 1), ('b', 2)]

## Generator objects

A generator is like a container that will only give you one element at a time. They are very useful because they
use up very little memory, allowing us to handle massing objects easily without wasting memory.

In [40]:
gen = (i**2 for i in range(10**40))

In [41]:
gen

<generator object <genexpr> at 0x10aa4fdb0>

In [42]:
next(gen)

0

In [43]:
next(gen)

1

In [44]:
next(gen)

4

In [45]:
for i in range(3):
    print(next(gen))

9
16
25


In [46]:
r = range(1, 20)
r

range(1, 20)

Looping through a generator also works:

In [47]:
for item in r:
    if item % 5 == 0:
        print(item)

5
10
15


When converting a generator to a list, be careful unless you know the size

In [48]:
list(r)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

## Controlling program flow

In [49]:
'a' if 3 < 4 else 'b'

'a'

In [50]:
'a' if 4 < 3 else 'b'

'b'

In [51]:
score = 95

if score >= 90:
    print('A')
    
elif score >= 80:
    print('B')
    
else:
    print('C')

A


### Looping

In [52]:
a = list(range(1, 20, 2))
a

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [53]:
for i in a:
    print(i, i**2)

1 1
3 9
5 25
7 49
9 81
11 121
13 169
15 225
17 289
19 361


In [54]:
max_count = 5
count = 0
while (count < max_count):
    print(count)
    count += 1

0
1
2
3
4


### Ways to Populate a List

- **Looping**

In [55]:
xs = [] # Create empty list 
for x in range(5):
    xs.append(x**2)
xs

[0, 1, 4, 9, 16]

In [56]:
xs = []
for x in range(5):
    if x % 2 == 0:
        xs.append(x**2)
xs

[0, 4, 16]

- List Comprehension

In [57]:
[x**2 for x in range(5)]

[0, 1, 4, 9, 16]

In [58]:
[x**2 for x in range(5) if x % 2 == 0]

[0, 4, 16]

- **Map and Filter**

In [59]:
list(map(lambda x: x**2, range(5)))

[0, 1, 4, 9, 16]

In [60]:
list(map(lambda x: x**2, filter(lambda x: x % 2 == 0, range(5))))

[0, 4, 16]

### User-defined functions

In [63]:
def my_function():
    """This function prints the Zen of Python """
    
    zen = """
    The Zen of Python, by Tim Peters

    Beautiful is better than ugly.
    Explicit is better than implicit.
    Simple is better than complex.
    Complex is better than complicated.
    Flat is better than nested.
    Sparse is better than dense.
    Readability counts.
    Special cases aren't special enough to break the rules.
    Although practicality beats purity.
    Errors should never pass silently.
    Unless explicitly silenced.
    In the face of ambiguity, refuse the temptation to guess.
    There should be one-- and preferably only one --obvious way to do it.
    Although that way may not be obvious at first unless you're Dutch.
    Now is better than never.
    Although never is often better than *right* now.
    If the implementation is hard to explain, it's a bad idea.
    If the implementation is easy to explain, it may be a good idea.
    Namespaces are one honking great idea -- let's do more of those!

    """
    return zen

In [64]:
z = my_function()
print(z)


    The Zen of Python, by Tim Peters

    Beautiful is better than ugly.
    Explicit is better than implicit.
    Simple is better than complex.
    Complex is better than complicated.
    Flat is better than nested.
    Sparse is better than dense.
    Readability counts.
    Special cases aren't special enough to break the rules.
    Although practicality beats purity.
    Errors should never pass silently.
    Unless explicitly silenced.
    In the face of ambiguity, refuse the temptation to guess.
    There should be one-- and preferably only one --obvious way to do it.
    Although that way may not be obvious at first unless you're Dutch.
    Now is better than never.
    Although never is often better than *right* now.
    If the implementation is hard to explain, it's a bad idea.
    If the implementation is easy to explain, it may be a good idea.
    Namespaces are one honking great idea -- let's do more of those!

    


In [65]:
def g(a, b):
    """Calculate the sum of a and b"""
    return a + b

In [66]:
g(4, 5)

9

- **Default arguments**

In [67]:
def h(a=0, b=1, c=2):
    """Calculates some random mathematical function"""
    return a + 3*b - c**2

In [68]:
h()

-1

In [69]:
h(1)

0

In [70]:
h(1, 2)

3

In [71]:
h(1, 2, 3)

-2

In [72]:
h(c=1, b=2, a=3)

8

## Using Libraries

In [73]:
import math

In [74]:
math.pi

3.141592653589793

In [75]:
import numpy as np

In [76]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [77]:
from numpy.random import rand

In [78]:
rand(4)

array([0.8434814 , 0.01343823, 0.59891758, 0.65251712])

### Built-in functions

Many functions are automatically imported into the main namespace. That is why we are able to use fucntions such as `range` or `list` without importing them first. 

In [79]:
dir(__builtin__)

['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BlockingIOError',
 'BrokenPipeError',
 'BufferError',
 'BytesWarning',
 'ChildProcessError',
 'ConnectionAbortedError',
 'ConnectionError',
 'ConnectionRefusedError',
 'ConnectionResetError',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError',
 'Exception',
 'False',
 'FileExistsError',
 'FileNotFoundError',
 'FloatingPointError',
 'FutureWarning',
 'GeneratorExit',
 'IOError',
 'ImportError',
 'ImportWarning',
 'IndentationError',
 'IndexError',
 'InterruptedError',
 'IsADirectoryError',
 'KeyError',
 'KeyboardInterrupt',
 'LookupError',
 'MemoryError',
 'ModuleNotFoundError',
 'NameError',
 'None',
 'NotADirectoryError',
 'NotImplemented',
 'NotImplementedError',
 'OSError',
 'OverflowError',
 'PendingDeprecationWarning',
 'PermissionError',
 'ProcessLookupError',
 'RecursionError',
 'ReferenceError',
 'ResourceWarning',
 'RuntimeError',
 'RuntimeWarning',
 'StopAsyncIteration',
 'StopIter

In [80]:
help(zip)

Help on class zip in module builtins:

class zip(object)
 |  zip(iter1 [,iter2 [...]]) --> zip object
 |  
 |  Return a zip object whose .__next__() method returns a tuple where
 |  the i-th element comes from the i-th iterable argument.  The .__next__()
 |  method continues until the shortest iterable in the argument sequence
 |  is exhausted and then it raises StopIteration.
 |  
 |  Methods defined here:
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __iter__(self, /)
 |      Implement iter(self).
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.
 |  
 |  __next__(self, /)
 |      Implement next(self).
 |  
 |  __reduce__(...)
 |      Return state information for pickling.



In [81]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [82]:
list(zip(['a', 'b', 'c'], range(10)))

[('a', 0), ('b', 1), ('c', 2)]

## Working with multi-dimensional arrays/matrices

In [83]:
import numpy as np

In [84]:
A = np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Indexing a matrix

In [85]:
A[0, 0] # 1st row, 1st column

0

In [86]:
A[2, 3] # 3rd row, 4th column

11

In [87]:
A[1] # 2nd row

array([4, 5, 6, 7])

In [88]:
A[:, 2] # 3rd column

array([ 2,  6, 10])

In [89]:
A[:2, 1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [90]:
A[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

### Vectorized functions

In [91]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
A * 10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [93]:
A.sum()

66

In [94]:
A.sum(axis=0) # Sum along vertical axis

array([12, 15, 18, 21])

In [95]:
A.sum(axis=1) # Sum along horizontal axis

array([ 6, 22, 38])

In [96]:
A.max(axis=0)

array([ 8,  9, 10, 11])

In [97]:
A.T # Transpose the matrix

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [98]:
A.T @ A # Dot product of Transpose of A with A

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

## Getting comfortable with error messages

In [99]:
foo

NameError: name 'foo' is not defined

In [ ]:
Sort([1, 2, 3])

In [100]:
for i in range(5):
print(i)

IndentationError: expected an indented block (<ipython-input-100-ff840fecd491>, line 2)

In [101]:
3 + '1' * 5

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
numbers = [1, 2, 0]
numbers

In [102]:
numbers[3]

NameError: name 'numbers' is not defined

In [103]:
contacts = {'bob': 'bob@quantumworld.com', 'alice': 'alice@quantumworld.com'}
contacts['alic']

KeyError: 'alic'

In [ ]:
x = 1 // 3
x

In [104]:
y = 3 // x

In [105]:
range(1, 2, 2, 3)

TypeError: range expected at most 3 arguments, got 4

In [106]:
open('yogi_bear.txt')

FileNotFoundError: [Errno 2] No such file or directory: 'yogi_bear.txt'

In [107]:
%load_ext watermark
%watermark

2019-03-24T01:17:54-06:00

CPython 3.6.7
IPython 7.1.1

compiler   : GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)
system     : Darwin
release    : 17.7.0
machine    : x86_64
processor  : i386
CPU cores  : 8
interpreter: 64bit
