# Getting Started with NumPy

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Getting-Started-with-NumPy" data-toc-modified-id="Getting-Started-with-NumPy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Getting Started with NumPy</a></span><ul class="toc-item"><li><span><a href="#Learning-Objectives" data-toc-modified-id="Learning-Objectives-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Learning Objectives</a></span></li><li><span><a href="#What-is-NumPy?" data-toc-modified-id="What-is-NumPy?-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>What is NumPy?</a></span></li><li><span><a href="#The-NumPy-Array-Object" data-toc-modified-id="The-NumPy-Array-Object-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>The NumPy Array Object</a></span></li><li><span><a href="#Data-types" data-toc-modified-id="Data-types-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Data types</a></span><ul class="toc-item"><li><span><a href="#Basic-Numerical-Data-Types-Available-in-NumPy" data-toc-modified-id="Basic-Numerical-Data-Types-Available-in-NumPy-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Basic Numerical Data Types Available in NumPy</a></span></li><li><span><a href="#Data-Type-Promotion" data-toc-modified-id="Data-Type-Promotion-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Data Type Promotion</a></span></li></ul></li><li><span><a href="#Going-Further" data-toc-modified-id="Going-Further-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Going Further</a></span></li></ul></li></ul></div>

## Learning Objectives

- Understand NumPy Array Object

## What is NumPy?



- NumPy provides the numerical backend for nearly every scientific or technical library for Python. In fact, NumPy is the foundation library for scientific computing in Python since it provides data structures and high-performing functions that the basic Python standard library cannot provide. Therefore, knowledge of this library is essential in terms of numerical calculations since its correct use can greatly influence the performance of your computations.

- NumPy provides the following additional features:
   - `Ndarray`: A multidimensional array much faster and more efficient
than those provided by the basic package of Python. The core of NumPy is implemented in C and provides efficient functions for manipulating and processing arrays.

  - `Element-wise computation`: A set of functions for performing this type of calculation with arrays and mathematical operations between arrays.

  - `Integration with other languages such as C, C++, and FORTRAN`: A
set of tools to integrate code developed with these programming
languages.

- At a first glance, NumPy arrays bear some resemblance to Python’s list data structure. But an important difference is that while Python lists are generic containers of objects:
  - NumPy arrays are homogenous and typed arrays of fixed size.
  - Homogenous means that all elements in the array have the same data type.
  - Fixed size means that an array cannot be resized (without creating a new array).


## The NumPy Array Object

- The core of the NumPy Library is one main object: `ndarray` (which stands for N-dimensional array)
- This object is a multi-dimensional homogeneous array with a predetermined number of items
- In addition to the data stored in the array, this data structure also contains important metadata about the array, such as its shape, size, data type, and other attributes. 


**Basic Attributes of the ndarray Class**

| Attribute | Description                                                                                              |
|-----------|----------------------------------------------------------------------------------------------------------|
| shape     | A tuple that contains the number of elements (i.e., the length)  for each dimension (axis) of the array. |
| size      | The total number elements in the array.                                                                  |
| ndim      | Number of dimensions (axes).                                                                             |
| nbytes    | Number of bytes used to store the data.                                                                  |
| dtype     | The data type of the elements in the array.                                                              |
| itemsize  | Defines teh size in bytes of each item in the array.                                                     |
| data      | A buffer containing the actual elements of the array.                                                    |

In order to use the NumPy library, we need to import it in our program. By convention,
the numPy module imported under the alias np, like so:

In [1]:
import numpy as np

After this, we can access functions and classes in the numpy module using the np
namespace. Throughout this notebook, we assume that the NumPy module is imported in
this way.

In [2]:
data = np.array([[10, 2], [5, 8], [1, 1]])
data

array([[10,  2],
       [ 5,  8],
       [ 1,  1]])

Here the ndarray instance data is created from a nested Python list using the
function `np.array`. More ways to create ndarray instances from data and from rules of
various kinds are introduced later in this tutorial. 

In [3]:
type(data)

numpy.ndarray

In [4]:
data.ndim

2

In [5]:
data.size

6

In [6]:
data.dtype

dtype('int64')

In [7]:
data.nbytes

48

In [8]:
data.itemsize

8

In [9]:
data.data

## Data types

- `dtype` attribute of the `ndarray` describes the data type of each element in the array.
- Since NumPy arrays are homogeneous, all elements have the same data type. 

### Basic Numerical Data Types Available in NumPy


| dtype   | Variants                            | Description                           |
|---------|-------------------------------------|---------------------------------------|
| int     | int8, int16, int32, int64           | Integers                              |
| uint    | uint8, uint16, uint32, uint64       | Unsigned (non-negative) integers      |
| bool    | Bool                                | Boolean (True or False)               |
| float   | float16, float32, float64, float128 | Floating-point numbers                |
| complex | complex64, complex128, complex256   | Complex-valued floating-point numbers |

Once a NumPy array is created, its `dtype` cannot be changed, other than by creating a new copy with type-casted array values

In [10]:
data = np.array([5, 9, 87], dtype=np.float32)
data

array([ 5.,  9., 87.], dtype=float32)

In [11]:
data = np.array(data, dtype=np.int32) # use np.array function for type-casting
data

array([ 5,  9, 87], dtype=int32)

In [12]:
data = np.array([5, 9, 87], dtype=np.float32)
data

array([ 5.,  9., 87.], dtype=float32)

In [13]:
data = data.astype(np.int32) # Use astype method of the ndarray class for type-casting
data

array([ 5,  9, 87], dtype=int32)

### Data Type Promotion

When working with NumPy arrays, the data type might get promoted from one type to another, if required by the operation. 
For instance, adding float-value and integer-valued arrays, the resulting array is a float-valued array:

In [14]:
arr1 = np.array([0, 2, 3], dtype=float)
arr1

array([0., 2., 3.])

In [15]:
arr2 = np.array([10, 20, 30], dtype=int)
arr2

array([10, 20, 30])

In [16]:
res = arr1 + arr2
res

array([10., 22., 33.])

In [17]:
res.dtype

dtype('float64')

<div class="alert alert-block alert-info">

In some cases, depending on the application and its requirements, it is essential to create arrays with data type appropriately set to right data type. The default data type is `float`:

<div>

In [18]:
np.sqrt(np.array([0, -1, 2]))

/Users/abanihi/opt/miniconda3/envs/dev/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([0.        ,        nan, 1.41421356])

In [19]:
np.sqrt(np.array([0, -1, 2], dtype=complex))

array([0.        +0.j, 0.        +1.j, 1.41421356+0.j])

Here, using the `np.sqrt` function to compute the square root of each element in
an array gives different results depending on the data type of the array. Only when the data type of the array is complex is the square root of `–1` resulting in the imaginary unit (denoted as `1j` in Python).

## Going Further


The NumPy library is the topic of several books, including the Guide to NumPy, by the creator of the NumPy T. Oliphant, available for free online at http://web.mit.edu/dvp/Public/numpybook.pdf, and *Numerical Python (2019)*, and *Python for Data Analysis (2017)*.



- [NumPy Reference Documentation](https://docs.scipy.org/doc/numpy/reference/)
- Robert Johansson, Numerical Python 2nd.Urayasu-shi, Apress, 2019.
- McKinney, Wes. Python for Data Analysis 2nd. Sebastopol: O’Reilly, 2017.


<div class="alert alert-block alert-success">
  <p>Next: <a href="02_memory_layout.ipynb">Memory Layout</a></p>
</div>